### ISSUE TITLE
Updates for Hero Section

### ISSUE THREAD

**Issue by jamestchavez** [jamestchavez/run-buddy#1]
# Updates for Hero Section

   ## Content Requirements
   * Heading: "Start Building Habits."
   * Text Body: Lorem ipsum text placeholder
   * Download new hero image for hero section

   ## Questions/suggestions for Design Team
   * What will be the marketing text?

**Comment by haroon-code-hub** [comment]
I made small changes and sent you a pull request regarding some updates. If you like it, You can assign this issue to me. :)

**Comment by jamestchavez** [comment]
@haroonsaeed82096 Thank you for the help! This is actually for a coding course I am taking so no action is needed. I appreciate the offer though :)

**Comment by haroon-code-hub** [comment]
You are welcome :) Good luck with course. :)
